import{a as c,i}from"./assets/vendor-2dcf4ad5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();c.defaults.headers.common["x-api-key"]="live_uT0RLJgJNg7OIzTQWFoQE9YFbtV4T1dSf8FWLCckGkuLSnpsxwktLbZvzXynYLdg";function p(){return c.get("https://api.thecatapi.com/v1/breeds").then(e=>e.data).catch(e=>{throw e})}function m(e){return c.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`).then(o=>o.data[0]).catch(o=>{throw o})}const u=document.querySelector(".breed-select"),a=document.createElement("option");a.value="";a.text="Choose Your Kitty";u.appendChild(a);function f(e){e.forEach(o=>{const n=document.createElement("option");n.value=o.id,n.text=o.name,u.appendChild(n)})}const d=document.querySelector(".cat-info");function h(e){d.innerHTML=`
  <div class="wrapper">
    <img class="picture" src="${e.url}" alt="${e.breeds[0].name}">
    <div class="text-content">
      <h1 class="breed">${e.breeds[0].name}</h1>
      <p class="description">${e.breeds[0].description}</p>
      <p class="description"><span class="temperament-span">Temperament:</span> ${e.breeds[0].temperament}</p>
      <a class="wiki-ref" href="${e.breeds[0].wikipedia_url}" target="_blank"> More Info...</a>
    </div>
  </div>
  `,d.style.display="block"}function g(){const e=document.querySelector(".breed-select").value,o=document.querySelector('.breed-select option[value=""]');o&&document.querySelector(".breed-select").removeChild(o),i.info({icon:"",close:!1,progressBar:!1,messageColor:"white",messageSize:"80",overlay:!0,overlayColor:"#22222a",backgroundColor:"transparent",message:"KITTY, KITTY, KITTY...",position:"center",transitionIn:"bounceInRight",transitionOut:"fadeOutRight",timeout:5e3}),m(e).then(n=>{i.hide({},document.querySelector(".iziToast")),h(n)}).catch(n=>{i.hide({},document.querySelector(".iziToast")),i.error({icon:"",close:!1,title:"",message:"Error fetching cat information. Try again!",position:"topRight",timeout:5e3}),console.error("Error fetching cat information:",n)})}document.querySelector(".breed-select").addEventListener("change",g);document.addEventListener("DOMContentLoaded",()=>{i.info({icon:"",close:!1,progressBar:!1,messageColor:"white",messageSize:"80",overlay:!0,overlayColor:"#22222a",backgroundColor:"transparent",message:"KITTY, KITTY, KITTY...",position:"center",transitionIn:"bounceInRight",transitionOut:"fadeOutRight",timeout:5e3}),p().then(e=>{i.hide({},document.querySelector(".iziToast")),f(e),document.querySelector(".breed-select").style.display="block"}).catch(e=>{i.hide({},document.querySelector(".iziToast")),i.error({icon:"",close:!1,title:"",message:"Error fetching cat breeds. Try again!",position:"topRight",timeout:5e3}),console.error("Error fetching breeds:",e)})});
//# sourceMappingURL=commonHelpers.js.map
