import{a,i as s}from"./assets/vendor-2dcf4ad5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();a.defaults.headers.common["x-api-key"]="live_uT0RLJgJNg7OIzTQWFoQE9YFbtV4T1dSf8FWLCckGkuLSnpsxwktLbZvzXynYLdg";function f(){return a.get("https://api.thecatapi.com/v1/breeds").then(e=>e.data).catch(e=>{throw e})}function h(e){return a.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`).then(o=>o.data[0]).catch(o=>{throw o})}const p=document.querySelector(".breed-select"),d=document.createElement("option");d.value="";d.text="Choose Your Kitty";p.appendChild(d);const i=document.querySelector(".js-error");i.style.display="none";function y(e){e.forEach(o=>{const n=document.createElement("option");n.value=o.id,n.text=o.name,p.appendChild(n)})}const c=document.querySelector(".cat-info");function g(e){c.innerHTML=`
  <div class="wrapper">
    <img class="picture" src="${e.url}" alt="${e.breeds[0].name}">
    <div class="text-content">
      <h1 class="breed">${e.breeds[0].name}</h1>
      <p class="description">${e.breeds[0].description}</p>
      <p class="description"><span class="temperament-span">Temperament:</span> ${e.breeds[0].temperament}</p>
      <a class="wiki-ref" href="${e.breeds[0].wikipedia_url}" target="_blank"> More Info...</a>
    </div>
  </div>
  `,c.style.display="block"}const m={icon:"",close:!1,progressBar:!1,messageColor:"white",messageSize:"80",overlay:!0,overlayColor:"#22222a",backgroundColor:"transparent",message:"KITTY, KITTY, KITTY...",position:"center",transitionIn:"bounceInRight",transitionOut:"fadeOutRight",timeout:5e3};function b(){const e=document.querySelector(".breed-select").value,o=document.querySelector('.breed-select option[value=""]');o&&document.querySelector(".breed-select").removeChild(o),s.show(m),h(e).then(n=>{s.hide({},document.querySelector(".iziToast")),g(n),i.style.display="none"}).catch(n=>{c.innerHTML="",i.style.display="block",s.hide({},document.querySelector(".iziToast")),s.error({icon:"",close:!1,title:"",message:"Error fetching cat information. Try again!",position:"topRight",timeout:5e3}),console.error(n)})}document.querySelector(".breed-select").addEventListener("change",b);document.addEventListener("DOMContentLoaded",()=>{s.show(m),f().then(e=>{s.hide({},document.querySelector(".iziToast")),y(e),document.querySelector(".breed-select").style.display="block",i.style.display="none"}).catch(e=>{s.hide({},document.querySelector(".iziToast")),c.innerHTML="",i.style.display="block",s.error({icon:"",close:!1,title:"",message:"Error fetching cat breeds. Try again!",position:"topRight",timeout:5e3}),console.error("Error fetching breeds:",e)})});
//# sourceMappingURL=commonHelpers.js.map
